### PR TITLE
Better logic for TLS 1.3 special handling

### LINKED ISSUE #174: globus-url-copy fails during GSI handshake with dCache when using TLS v1.3
When testing with the current tip of gct `master` branch (commit `2217e6ec24`) I cannot upload data to dCache.

I see the following error:

```
✔ 19:04:11 build [master …64] $ gass/copy/source/globus-url-copy file:///bin/bash gsiftp://localhost/public/test-1

error: globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed to generate output token

✘ 19:04:14 build [master …64] $ 
```

I've tested this will all currently supported versions of dCache: the problem is present (on my laptop) in all cases.

Note that the above command is statically built:

```
✘ 19:04:14 build [master …64] $ ldd gass/copy/source/globus-url-copy 
        not a dynamic executable
✘ 19:05:20 build [master …64] $ 
```

Therefore, it does not depends on external globus libraries (`libglobus_*`), making testing easier.

I ran `git bisect run` with a script that builds gct and runs the above `globus-url-copy` command.  The run completed with the following output:
```
4e76b43b0e3cba64f61522444016ac462c3dc7ae is the first bad commit
commit 4e76b43b0e3cba64f61522444016ac462c3dc7ae
Author: Mattias Ellert <mattias.ellert@physics.uu.se>
Date:   Thu Mar 25 10:42:32 2021 +0100

    TLS v1.3 sends 2 session tokens after the handshake is completed
    We need to recieve them before continuing with the GSI proxy

 .../source/library/globus_gsi_gss_constants.h      |  2 +
 gsi/gssapi/source/library/init_sec_context.c       | 74 +++++++++++++++++++++-
 2 files changed, 75 insertions(+), 1 deletion(-)
bisect run success
✔ 18:12:08 gct [:b2e6edde3|BISECTING …4] $
```

### PR DESCRIPTION
**Pull request by ellert**
Fixes #174.

### CODE REVIEW

File: gsi/gssapi/source/library/init_sec_context.c [hunk 1]
```diff
@@ -367,15 +372,65 @@ GSS_CALLCONV gss_init_sec_context(
 
         /*
          * TLS v1.3 sends 2 session tokens after the handshake is completed.
+         * If we are using a token source that sends one SSL token at a time
+         * (e.g. the file based token source in globus-gss-assist)
+         * these sessions tokens will not be seen by BIO_do_handshake before
```
Comment (fscheiner) [inline gsi/gssapi/source/library/init_sec_context.c:377]: Small typo, but no need to rebase your PR:

"these sessions tokens" => "these session tokens"

**Review by fscheiner — APPROVED** [review]
@ellert:
Great work, Mattias! Thanks a lot for fixing that issue with dCache.

I now have successfully tested a manually compiled version based on your [`better-tls-1.3-logic`](https://github.com/ellert/gct/tree/better-tls-1.3-logic) branch with:

```
GLOBUS_GSSAPI_MAX_TLS_PROTOCOL=TLS1_3_VERSION GLOBUS_GSSAPI_DEBUG_LEVEL=2 ./globus-url-copy -dbg -list [...]
```

...on both Fedora 34 and openSUSE Leap 15.3 against:

* a GCT v6.2.20210826 based Globus GridFTP Server on CentOS 7 (works using TLS v1.2)
* a GCT v6.2.20210826 based Globus GridFTP Server on RockyLinux 8 (works using TLS v1.3)
* the [`prometheus.desy.de` dCache instance](https://confluence.desy.de/pages/viewpage.action?pageId=228761933) (works using TLS v1.3)

Can't say much about your changes other than they make it work with dCache again.

File: gsi/gssapi/source/library/init_sec_context.c (hunk 1 above)
Comment (ellert) [reply gsi/gssapi/source/library/init_sec_context.c]: Thank you, I fixed the typo since I had to rebase one of the PRs anyway.
